### ISSUE TITLE
Concerning vendor support: Please modify the vendor check function to probe for Clevo, not a specific sub-vendor. 

### ISSUE THREAD

**Issue by Brainiarc7** [tuxedocomputers/tuxedo-fan-control#11]
Hello there,

In the documentation, there's an option for [disabling vendor checking](https://github.com/tuxedocomputers/tuxedo-fan-control/blob/master/docs/dev/dev_manual.md#novendorcheck), tied to [this](https://github.com/tuxedocomputers/tuxedo-fan-control/blob/master/src/common/system.ts#L83) in the source code.

Considering that Tuxedo hardware is derived from existing Clevo-based lines, wouldn't it be safer to check for a DMI string that matches Clevo's, instead of a specific sub-vendor such as Tuxedo computers?
That would also allow for the deprecation of the `--novendorcheck` option (that might be unsafe if a user were to do this on a non-Clevo SKU).

I raise this issue in the hope that this check will be changed to only probe for Clevo devices, enhancing usability by default without relying on potentially unsafe flags to do the same.

**Comment by tuxedochris** [comment]
Hi Brainiarc,

thanks for the issue and suggestion, but we must say no to this.
We develop and testing this software on our TUXEDO Notebooks. In some cases we have a other Bios or EC for our devices. 

This is also the question of warranty, or liability. We can not testing the software of all clevo and sub-vendor devices. This is the reason, why we add  the flag--novendorcheck for the all other vendors.

Cheers
Chris

**Comment by Brainiarc7** [comment]
Makes sense.
