### ISSUE TITLE
Overclock mode

### ISSUE THREAD

**Issue by copy** [tuxedocomputers/tuxedo-fan-control#12]
Clevo Control Center has a mode that automatically sets the fan speed slightly higher than the default automatic mode. I like this mode because it keeps my machine cooler under high load and isn't too loud under normal load. Is this mode available via the EC registers and could it be added to the program?

**Comment by tuxedochris** [comment]
Hi copy,

we working currently on a TUXEDO Control Center for Linux and we have so task in the pipeline. For the TUXEDO Fan Control, it is not planned to implement this.

Cheers
Chris
