### ISSUE TITLE
Request: Auto Update with suggestion

### ISSUE THREAD

**Issue by GJRTimmer** [tuxedocomputers/tuxedo-fan-control#17]
Would you please look into using: https://www.update.rocks/
This is an update service for electron app, the beauty of it is that it is free for open source projects.

This will allow auto updating of the app, I'm not affiliated with update.rocks in anyway.

**Comment by soupdiver** [comment]
Hey there,
I'm one of the creators of UpdateRocks. Should you need any help to get started, feel free to reach out. I'm happy to help :)
