### ISSUE TITLE
daemon fails to start on Arch

### ISSUE THREAD

**Issue by adsworth** [tuxedocomputers/tuxedo-fan-control#2]
Hi,

I just built the daemon and when I try to run it I get the following error:
tuxedofancontrol.service - TUXEDO Fan Control
   Loaded: loaded (/etc/systemd/system/tuxedofancontrol.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2018-11-27 11:19:09 CET; 1min 12s ago
  Process: 12663 ExecStart=/bin/bash -c Xvfb :99 & export DISPLAY=:99 && /mnt/datadisk/data/projects/tuxedo-fan-control/output/dist --startdaemon (code=exited, status=126)

Nov 27 11:19:09 corebooklet systemd[1]: Starting TUXEDO Fan Control...
Nov 27 11:19:09 corebooklet bash[12663]: /bin/bash: /mnt/datadisk/data/projects/tuxedo-fan-control/output/dist: Is a directory
Nov 27 11:19:09 corebooklet systemd[1]: tuxedofancontrol.service: Control process exited, code=exited status=126
Nov 27 11:19:09 corebooklet systemd[1]: tuxedofancontrol.service: Failed with result 'exit-code'.
Nov 27 11:19:09 corebooklet systemd[1]: Failed to start TUXEDO Fan Control.

Any idea what the issue might be?

Thanks
   Adi

**Comment by tuxedochris** [comment]
Hi Adi,

the problem is the Path. The Error output say "/mnt/datadisk/data/projects/tuxedo-fan-control/output/dist: Is a directory" and that is correcly. 
The TUXEDO Fan Control is a electron app and that need a electron binary to start the application. You can change the file path in the systemd service file or (i recommed this), you create a AppImage and use this, and rewrite the service file over ui (Remove System Unit file and create it again).

Cheers
Chris

**Comment by adsworth** [comment]
Hi,

that also doesn't seem to work. If I create the service file using the AppImage the binary points to a directoy in /tmp.

```
# /etc/systemd/system/tuxedofancontrol.service
[Unit]
Description=TUXEDO Fan Control

[Service]
Type=forking
ExecStart=/bin/bash -c "Xvfb :99 & export DISPLAY=:99 && /tmp/.mount_tuxedoQLuJwA/resources/app.asar --startdaemon"
ExecStop=/bin/bash -c "Xvfb :99 & export DISPLAY=:99 && /tmp/.mount_tuxedoQLuJwA/resources/app.asar --stopdaemon"
ExecReload=/bin/bash -c "Xvfb :99 & export DISPLAY=:99 && /tmp/.mount_tuxedoQLuJwA/resources/app.asar --restartdaemon"

[Install]
WantedBy=multi-user.target
```
When I run the AppImage using sudo I get asked if I want to move the AppImage to /root/Applications and then restarte the AppImage.

**Comment by alexanderdurr** [comment]
> I've got it working by editing the service file directly.

Hi  @adsworth ,
can you tell us what path you had to choose?
Is it `/opt/tuxedofancontrol/tuxedofanctontrol ` or `/opt/tuxedofancontrol/resources/app.asar` ?

**Comment by adsworth** [comment]
Hi @alexanderdurr ,

I must admit I don't remember. I'm currently running the unpacked version directly from my build directory. AFAIR, it was app.asar.
If I remember corretly if you run the tuxedofancontrol binary directly then it unpacks everything to /tmp and actually executes from there.
