### ISSUE TITLE
Change Fan Speed and Temperature settings

### ISSUE THREAD

**Issue by magdesign** [tuxedocomputers/tuxedo-fan-control#23]
Having a Tuxedo TUXEDO Book XP1610
Intel® Core™ i7-9750H CPU @ 2.60GHz × 12 
GeForce RTX 2060/PCIe/SSE2
Ubuntu 18.04.3 LTS

The tuxedofancontrol constantly speeding up the CPU FAN Duty to 85% for 2 seconds, then to 17% for 2 seconds and then up to 85% again for a few seconds. This behavior is going all day long and is much more annoying than having the fan constantly running at 73% speed (when disabling the Daemon).

Is there a chance to change the scripts behavior?
For example a linear speed down of the fan duty 
e.g.: from 85% CPU FAN Duty going down to 60% while constantly checking the temperature and if its still below the edge, going down to 40% and so on. 
Lets say: A bit less aggressive.

BTW.
I am not able tho set the CPU FAN Duty as seen in the screenshot [here](https://github.com/tuxedocomputers/tuxedo-fan-control/blob/master/docs/user/user_manual.md#systemd---control-the-daemon), the set option is not visible.

![Screenshot from 2019-08-14 11-13-54](https://user-images.githubusercontent.com/5273166/63009399-b26d9f80-be84-11e9-8517-e2e9747d3f8e.png)

**Comment by magdesign** [comment]
I currently use this workaround an my brandnew Tuxedo Laptop:
https://gist.github.com/magdesign/1f8d554c391e0c2658c1bde58b687636

**Comment by MarvinBlstrli** [comment]
I can confirm this behavior on my TUXEDO InfinityBook Pro 15 v4  with Debian 10

**Comment by tuxedoxt** [comment]
The described behaviour has been addressed in TCC (TUXEDO Control Center). TCC effectively replaces TFC as of now and has improvements to hardware control, smoother control algorithm, and multiple fan profiles.
