### ISSUE TITLE
Temp checks

### ISSUE THREAD

**Issue by TheRealAgentK** [tuxedocomputers/tuxedo-fan-control#25]
Hey Tuxedo-Team!

I'm on an InfinityBook Pro 15v5 and I find fancontrol a bit too trigger happy.

For instance - I launch something, there's a short CPU/temp burst, fans go wild for 2 seconds, then calm down to nothing again. 

I'd prefer to be able to maybe check for temp changes less often (for instance every 2,3,4,5 etc seconds) instead of every second.

If I built that as a configurable switch, would that be something you'd be interested as a PR?

**Comment by tuxedoxt** [comment]
Hello,

we generally welcome contribution. In this case however I do not necessarily agree that it is a good idea to delay spinning up the fans.

There are improvements being worked on though. We are in the process of incorporating fan control into a new application with more abilities. For your case the solution in the future could be a combination of a different fan profile/power profile.

**Comment by tuxedoxt** [comment]
Hello again,

the "triggerhappyness" has gotten improvements, albeit not in this application. TFC is now finally replaced by TCC (TUXEDO Control Center). Algorithm/control improvements as well as possibility of different profiles are available in TCC.

**Comment by TheRealAgentK** [comment]
Just grabbed TCC and its *SO MUCH BETTER* on my IB Pro 15v5.

Thanks a lot, team!
