### ISSUE TITLE
control both GPU fans on XP1508

### ISSUE THREAD

**Issue by sjeske** [tuxedocomputers/tuxedo-fan-control#3]
On Tuxedo XP1508 setup with nvidia 1060 only one of two gpu fans is controlled. Could you determine through witch hardware registers the second fan can be controlled?

**Comment by tuxedochris** [comment]
Hi,

this is a known issues (Is a note in the dev manual), with a high priority, and we work an this.
We plan currently, in the next few weeks, release the new version 0.1.3. 

Cheers
Chris

**Comment by tuxedochris** [comment]
Hi,

we have implement this feature in the current version.

Cheers
Chris
