### ISSUE TITLE
Segmentation fault at starting the tuxedofancontrol.service

### ISSUE THREAD

**Issue by hekrause** [tuxedocomputers/tuxedo-fan-control#31]
I bought the computer right over new year and tried to install this tool via the ppa's, via source and with the ```tuxedo.sh``` script. 

I can't understand why such a important tool is build in that way and more important **still is**.
There was a guy in mid 2019 saying there will be a better version(@tuxedoxt in https://github.com/tuxedocomputers/tuxedo-fan-control/issues/21#issuecomment-514509971_) but still there is no better solution. 

For me this is a really huge downside for the @tuxedocomputers company. It seems that the only stable configuration was the preinstalled TUXEDO_OS, which i wanted to switch against Ubuntu Budgie 18.04 LTS. There should be no problem([source](https://www.tuxedocomputers.com/de/Infos/Hilfe-Support/Anleitungen/TUXEDO-Fan-Control-installieren.tuxedo)).

I'am a little bit concerned about how my computer will work without this tool.

### My try to install tuxedofancontrol via surce
``` shell
inxi -Fs
```
My system information:
![grafik](https://user-images.githubusercontent.com/17926729/72899383-2fe7e680-3d26-11ea-8f6f-40069869deb3.png)

``` shell
npm install
```
![grafik](https://user-images.githubusercontent.com/17926729/72899020-7c7ef200-3d25-11ea-86c2-357e67021932.png)

``` shell
sudo dpkg -i output/build/*.deb
```
![grafik](https://user-images.githubusercontent.com/17926729/72900246-d2ed3000-3d27-11ea-9e2c-615c69ccd8aa.png)

After the errors occured i tried to make thing by hand with first creating the systemd-servicefile:
```shell
tuxedofancontrol --createunitfile
```
Enabling the service:
```shell
sudo systemctl enable tuxedofancontrol
```

Then when the service tries to start the is a segmentation fault in the binary.
```shell
sudo systemctl status tuxedofancontrol
```

![grafik](https://user-images.githubusercontent.com/17926729/72900683-a4bc2000-3d28-11ea-92a2-be581a67a2b2.png)

**Comment by tuxedoxt** [comment]
Hello, a recent update to something (at least verified in Ubuntu) related to Xvfb broke running the application with Xvfb, resulting in a segfault. Since the installation of the program unfortunately depends on this, the installation broke as well (the part installing the service).

Again, there are many reasons to move away from this way and the previous mention of a rewrite is still valid and has progressed quite a bit. In the meantime this program will be patched with a workaround.

There is no reason to be concerned that the tool is not working however. The computer will work perfectly fine without it, albeit slightly louder depending on model.

**Comment by tuxedoxt** [comment]
Hello again, I have made an attempt at a workaround solution. If you build yourself you can just pull the latest version and build this. It works in the test cases I have atm. Should be available in repo soon. Might need a reboot after package install.

Let me know how it goes.

**Comment by hekrause** [comment]
Hi,

It works! :-) Thank you for your quick response and the fix.
Sorry for the little salty rant but the Notebook is brand new and was loud as hell without this tool. 

The service state after the fix.
![grafik](https://user-images.githubusercontent.com/17926729/73125480-77c97080-3fa7-11ea-93fb-ad9c8d5bd8cc.png)
