### ISSUE TITLE
Build Errors on Mint 19

### ISSUE THREAD

**Issue by Xephrey** [tuxedocomputers/tuxedo-fan-control#4]
npm run build returned with the following errors:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tuxedofancontrol@0.1.2 build: `npm run clean && npm install && ng build --base-href . && ts-node ./scripts/build.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tuxedofancontrol@0.1.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I actually have an TUXEDO Book XC1708 equivalent - a Clevo PA71ES-G. Any chance there's a finished compiled binary for that specific model that I can use?

Thanks.

**Comment by tuxedochris** [comment]
Hi Xephrey,

which version of node use you and have you a build.log?

Cheers
Chris

**Comment by Xephrey** [comment]
Hey tuxedochris

I ended up finding the address to the support section's ftp. I downloaded and installed the deb file of tuxedofancontrol from there. The daemon appears to be active and running. Where do I go to create a custom fan curve?

Thanks

**Comment by tuxedochris** [comment]
Hi Xephrey,

you must create a new entry in the fantables.json and then must recompile the application. We have dont integrate to create or modify fantables on the fly.
We support only our fan tables and TUXEDO devices. This means that you are doing it all at your own risk.

Cheers
Chris
